# -*- coding: utf-8 -*-
"""Final Project_DEPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOxdr6mqJhJBukBV7A1yNQy2azcyXCmy
"""

# ✅ إعادة تعريف المكتبات المطلوبة
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================
# 📂 Load Dataset
# ============================================

from google.colab import files
uploaded = files.upload()  # ارفع ملف CSV من جهازك

import pandas as pd

# اقرأ الملف متخطي أول صفين
df = pd.read_excel("cleaned railway data (1).xlsx")  # أو .csv حسب نوع الملف

# اعرض أول 5 صفوف
df.head()

df.dropna(how='all', inplace=True)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Delay'] = pd.to_numeric(df['Delay'], errors='coerce')

date_cols = ['Date_of_Purchase', 'Date_of_Journey']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print(df.info())

df.fillna({'Purchase_Type':'Unknown',
           'Payment_Method':'Unknown',
           'Railcard':'None',
           'Journey_Status':'Unknown'}, inplace=True)

label_cols = ['Purchase_Type', 'Payment_Method', 'Railcard',
              'Ticket_Class', 'Ticket_Type', 'Departure_Station',
              'Arrival_Destination', 'Journey_Status', 'Reason_for_Delay',
              'Refund_Request']

encoder = LabelEncoder()
for col in label_cols:
    df[col] = encoder.fit_transform(df[col].astype(str))

X = df[['Purchase_Type','Payment_Method','Railcard','Ticket_Class',
        'Ticket_Type','Price','Departure_Station','Arrival_Destination','Delay']]
y = df['Journey_Status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

# مصفوفة الارتباك
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# تحليل العلاقة بين التأخير والسعر
plt.figure(figsize=(8,5))
sns.scatterplot(x='Price', y='Delay', hue='Journey_Status', data=df)
plt.title("Relation Between Ticket Price and Delay")
plt.show()

# أهم العوامل اللي بتأثر على حالة الرحلة
importances = pd.Series(model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).plot(kind='bar', figsize=(8,5), title="Feature Importance")
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='Journey_Status', y='Price', data=df, palette='coolwarm')
plt.title("Average Ticket Price per Journey Status")
plt.show()

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train_scaled, y_train, cv=5)
print("🔍 Cross-Validation Accuracy:", scores.mean())

from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_scaled, y_train)
dt_pred = dt_model.predict(X_test_scaled)

print("🌳 Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

importances.sort_values().plot(kind='barh', figsize=(8,5), color='coral')
plt.title("Feature Importance (Horizontal View)")
plt.show()

## 💡 الاستنتاج النهائي:
#من خلال تحليل بيانات الرحلات وجدنا أن:
#- **سعر التذكرة** و**الوجهة** هما العاملان الأكثر تأثيرًا على احتمالية تأخير الرحلة.
#- الرحلات الأغلى سعرًا تميل إلى الالتزام أكثر بالمواعيد.
#- نموذج Random Forest حقق دقة عالية تجاوزت 91%.
#- يمكن للشركة استخدام هذا النموذج للتنبؤ بالرحلات المعرضة للتأخير مسبقًا وتحسين رضا العملاء.